require 'date'
require 'ostruct'
require 'optparse'

require 'log-merge/reverse_file_reader'
require 'log-merge/log_reader'
require 'log-merge/reverse_log_reader'
require 'log-merge/log_line'
require 'log-merge/log_combiner'
require 'log-merge/merge_cli'
require 'log-merge/index'
